name: CI Template

on:
  workflow_call:

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        working-directory: backend
        run: yarn install --frozen-lockfile

      - name: Run build
        working-directory: backend
        run: yarn build
      
      - name: Run tests
        working-directory: backend
        run: yarn test
      
      - name: Run linter
        working-directory: backend
        run: yarn lint:check
  
  build-and-test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: frontend
        run: yarn install --frozen-lockfile

      - name: Run build
        working-directory: frontend
        run: yarn build

      - name: Run tests
        working-directory: frontend
        run: yarn test
      
      - name: Run linter
        working-directory: frontend
        run: yarn lint:check
