name: CI Template

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: frontend
        run: yarn install --frozen-lockfile

      - name: Run build
        working-directory: frontend
        run: yarn build

      - name: Run tests
        working-directory: frontend
        run: yarn test
      
      - name: Run coverage
        working-directory: frontend
        run: yarn coverage
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Run linter
        working-directory: frontend
        run: yarn lint:check
