name: deploy-production

on:
  push:
    branches: [ main ]

jobs:
  run-ci:
    uses: ./.github/workflows/ci-template.yml
    with: {}
  deploy-prod:
    runs-on: ubuntu-latest
    needs: run-ci
    steps:
      - name: Deploy APP on production
        run: |
          curl ${{ secrets.RENDER_APP_PROD_WEBHOOK }}
  release-prod:
    uses: ./.github/workflows/release.yml
    needs: deploy-prod
    secrets: inherit
