name: Pull-Requests CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:
    ci:
        uses: ./.github/workflows/ci-template.yml
        with: {}
    lighthouse:
        uses: ./.github/workflows/lighthouse-template.yml
        secrets: inherit